# Generated by Django 5.0.6 on 2024-10-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_categoria_slug_mueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='mueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='muebles/'),
        ),
    ]
