version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=casablanca_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Tunja2021*
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app/theme/static_src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=casablanca_database
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Tunja2021*
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
