# Generated by Django 5.0.6 on 2024-06-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='tipo',
            field=models.CharField(choices=[('SALARIO', 'Salario'), ('NEGOCIO', 'Negocio'), ('INVERSION', 'Inversión')], default='SALARIO', max_length=50),
            preserve_default=False,
        ),
    ]
