version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=casablanca_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Tunja2021*
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
